---
- name: reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
    enabled: true
